version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: docai
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

